### ISSUE TITLE
Trace Pre-processing  TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Grace-TL** [Princeton-Cabernet/BeauCoup#1]
when running ` python3 py/trace_prep.py ../../dataset/pcap/test.pcap test/caida0.npy`  I have the following error:

`Traceback (most recent call last):
  File "py/trace_prep.py", line 22, in <module>
    nparray = lib_eval.parse_pcap_into_npy(args.PCAP_filename, args.count, args.verbose)
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 79, in parse_pcap_into_npy
    packets_numerical.append(tuple(to_list(pdict)))
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 73, in to_list
    line[i]=int(line[i])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

Note that test.pcap is a small pcap file extract from CAIDA18 traces

**Comment by chenxiaoqino** [comment]
Hi Grace, there are a few potential causes. I suggest testing with a smaller "--count" parameter, e.g., "--count=100".

1. It's most likely `pkt[TCP].checksum` or `pkt[UDP].checksum` returned `None`. I use scapy 2.4.2; what is your scapy version? I suspect an earlier version of scapy has different reading result. 
2. Perhaps there is one malformed packet. I tested our script on five different files `equinix-nyc.dirA.20180315-130[1-5]00` of the CAIDA 18 packet and can't reproduce the issue. Could you share the particular trace's filename that you encountered the issue?

**Comment by Grace-TL** [comment]
Hi Xiaoqi,

1. With "--count=100", I can preprocess the pcap file successfully.
2. My scapy version is 2.4.3, the OS version is Ununtu 14.04
3. The pcap file I use is equinix-nyc.dirA.20180719-130000.UTC.anon.pcap.  The output is as follows: 

`$ python3  py/trace_prep.py ../../dataset/pcap/equinix-nyc.dirA.20180719-130000.UTC.anon.pcap test/caida0.npy 
Traceback (most recent call last):
  File "py/trace_prep.py", line 22, in <module>
    nparray = lib_eval.parse_pcap_into_npy(args.PCAP_filename, args.count, args.verbose)
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 75, in parse_pcap_into_npy
    packets_numerical.append(tuple(to_list(pdict)))
  File "/home/ltang/Workspace/research/store/BeauCoup/py/core/lib_eval.py", line 73, in to_list
    line[i]=int(line[i])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by chenxiaoqino** [comment]
Hi Grace,

1. It might be due to the small percentage of IPv6 packets present in this pcap; however I think IPv6 packets will generate a row full of -1s with no problem.
2. Another possible issue is the script costs a few gigabytes of memory, and will fail in weird ways when running out of memory. Please try running with a small count (e.g., use only the first 100k packets), or on a server / desktop with sufficient memory (at least 16GB to 32GB). I tried running the script on `equinix-nyc.dirA.20180719-130000.UTC.anon.pcap` and has successfully parsed the first 4M packets with no problem. I estimate it costs at least 12GB of memory to parse the full 30M packets in this 1-minute pcap file.

I am running the script overnight on `equinix-nyc.dirA.20180719-130000.UTC.anon.pcap` to test our script and try to reproduce the issue.

**Comment by chenxiaoqino** [comment]
Update: I have reproduced the error after packet #6540000. I'll investigate further.

**Comment by chenxiaoqino** [comment]
Packet #6547167 has IPv4, then IPv6, then TCP header; scapy returns "None" for `pkt[TCP].checksum`. I have added a fix for such situation. Tested on `equinix-nyc.dirA.20180719-130000.UTC.anon.pcap`.

**Comment by Grace-TL** [comment]
Hi Xiaoqi,

Now I can preprocess the pcap file successfully. Thank you!
